 version: "3.8"
 services:
   langchain-app:
     image: kbservice:latest  # Use the image from the registry
     container_name: langchain_flask_app
     ports:
       - "5601:5601"
     environment:
       - INDEX_DIR=/app/faissdb
     volumes:
       - ./uploads/caisuxin/faissdb:/app/faissdb